#ifndef PIXELSHADER_H
#define PIXELSHADER_H

#define SHADER_PROGRAM_TEMPLATE_HEADER
#define SHADER_PROGRAM_TEMPLATE_CLASS_NAME PixelShader
#define SHADER_PROGRAM_TEMPLATE_TYPE_PIXEL

#include "ShaderProgramTemplate.h"

#endif //PIXELSHADER_H
